# Generated by Django 4.2 on 2023-05-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us_feedback',
            old_name='c_exprience',
            new_name='c_experience',
        ),
    ]
